version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  fastapi-app:
    build: .
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgres://myuser:mysecretpassword@db:5432/mydatabase
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
